In [1]:
import numpy as np

In [2]:
nd = np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])
nd

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [3]:
# 平均值
nd.mean()

5.5

In [4]:
nd.max()  # shift + tab查看方法参数

10

In [5]:
nd.min()

1

In [6]:
# 返回数组元素沿给定轴的标准差。标准差的平方等于方差。
nd.std()

2.8722813232690143

In [7]:
# 方差。方差的开方等于标准差。
nd.var()

8.25

In [8]:
# 开方
np.power(5, 0.5)

2.23606797749979

In [9]:
# 开方
np.power(8.25, 0.5)  # 方差的开方等于标准差。

2.8722813232690143

In [10]:
# 加法
np.add(nd, 100)

array([[102, 104, 106, 108, 110],
       [101, 103, 105, 107, 109]])

In [11]:
# 减法
np.subtract(nd, 100)

array([[-98, -96, -94, -92, -90],
       [-99, -97, -95, -93, -91]])

In [12]:
# 乘法
np.multiply(nd, 100)

array([[ 200,  400,  600,  800, 1000],
       [ 100,  300,  500,  700,  900]])

In [13]:
# 除法
np.divide(nd, 100)

array([[0.02, 0.04, 0.06, 0.08, 0.1 ],
       [0.01, 0.03, 0.05, 0.07, 0.09]])

In [14]:
# 三角函数
np.sin(np.pi/2)

1.0

In [15]:
np.e

2.718281828459045

In [16]:
# 计算输入数组中所有元素的指数。自然底数e为底，2.718。
np.exp(2)

7.38905609893065

In [17]:
# 逐个元素计算自然对数
np.log(7.38905609893065)

2.0